# Generated by Django 3.1.5 on 2021-02-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210221_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numberPurchased',
            new_name='numberSold',
        ),
    ]
