# Generated by Django 3.1.5 on 2021-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210221_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='books',
            field=models.ManyToManyField(default=None, related_name='categories', to='books.Book'),
        ),
    ]
