# Generated by Django 3.1.5 on 2021-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210221_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='books',
            field=models.ManyToManyField(related_name='specials', to='books.Book'),
        ),
    ]
