# Generated by Django 3.1.5 on 2021-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210221_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='special',
            name='logo',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='special',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='specials', to='books.Book'),
        ),
    ]
